export interface PersonaNatural{
    contribuyente: {
        ubigeo: string,
        cod_tipo_contribuyente: string,
        cod_tipo_via: string,
        domicilio: string,
        nro_domicilio: string,
        referencia_domicilio: string,
        telefono_principal: string,
        telefono_secundario: string,
        correo_electronico: string,
        personanatural: {
            nombre: string,
            apellido_paterno: string,
            apellido_materno: string,
            cod_tipo_doc_identidad: string,
            num_documento_identidad: string,
            cod_sexo: string,
            fec_nacimiento: string,
            conyuge: {
                nombre: string,
                apellido_paterno: string,
                apellido_materno: string,
                cod_tipo_doc_identidad: string,
                num_documento_identidad: string,
                cod_estado_civil: string,
            },
            cod_estado_civil: string,
            fec_reg: string,
            fec_mod: string,
            usuario_mod_id: string,
            usuario_reg_id: string,
        }
    },
    predio: number,
    cod_tipo_uso: string,
    fec_inicio_vigencia: string,
    fec_fin_vigencia: string,
    cod_tipo_propietario: string,    
    porc_propiedad: string,
}